### ISSUE TITLE
Sync Alternate Schedules w/ Tutorbook

### ISSUE THREAD

**Issue by nicholaschiang** [Orbiit/gunn-web-app#111]
This isn't really an issue (at least for you guys), but I couldn't think of a better place to put it, so here it is:

I'd like to sync [Tutorbook](https://github.com/nicholaschiang/tutorbook) with [UGWA](https://github.com/Orbiit/gunn-web-app/)s bell schedule such that alternate schedules (and the actual duration's of tutoring appointments made during class periods) are always up-to-date (if you're interested, the actual app can be found [here](https://gunn.tutorbook.app)).

I was looking through your [parser implementation](https://github.com/Orbiit/gunn-web-app/blob/master/js/altScheduleGenerator.js) and decided that it would probably be best not to reinvent the wheel and just use what's already been done here (i.e. your Google Calendar integration).

@SheepTester Let me know if you're interested in helping out.

**Comment by SheepTester** [comment]
What would this require?

**Comment by nicholaschiang** [comment]
Some questions for you before I suggest anything uninformed:

- How are you guys updating your alternate schedules?
- Do you call that Google Calendar API every time a client opens the app?
- Or do you have to update it manually and then push those changes to the client?

Ideally, we would be able to setup some kind of webhook that would update my version of the schedule whenever UGWA's schedule is updated. Any suggestions?

**Comment by SheepTester** [comment]
Since UGWA is run on Github pages, there's no backend. This means that all alternate schedule calculations must be done by every user for themselves. New users fetch for all events during the school year from the Google Calendar API using about six requests with different filter queries (eg `extended` or `schedule`) to get all the alternate and SELF schedules for the whole year. Then, whenever a user views a day (eg when the app first starts or the user views a different day), the app fetches all of the events for that day in a single request to both display to the user and update the alternate schedule for the day if necessary.

(the schedule usually doesn't change after the year starts, though the epic CAASPP week is announced a few weeks before, and assemblies from speakers can be spontaneous)

A backend version of the alternate schedule parser could initialize its schedules similarly, then every day (or every week) refetch to check the schedules for the day (or week) just in case. However, this can't be done on Github pages because Github pages doesn't support custom backend scripts

Perhaps I could make a node package for this

**Comment by nicholaschiang** [comment]
If you could make that school calendar/schedule parser a node package, that would be great (and then I'd just use that package on my backend to maintain a client callable schedule REST API). Something like:

```javascript
const schedule = require('sheeptesters-awesome-new-gunn-schedule-package');
await schedule.update(); // Grab the most recent schedule for the week
assert(schedule.monday = {'A Period': { 'start': '8:25 AM', 'end': '9:45 AM'}})
```
Or whatever makes the most sense to you (just make sure that your documentation makes sense).

**Comment by anematode** [comment]
I am scared of node.js

![image](https://user-images.githubusercontent.com/26530804/68700685-2843de80-053a-11ea-94c9-3c05c61d4fec.png)

Save me

**Comment by SheepTester** [comment]
> If you could make that school calendar/schedule parser a node package, that would be great (and then I'd just use that package on my backend to maintain a client callable schedule REST API). Something like:
> 
> ```js
> const schedule = require('sheeptesters-awesome-new-gunn-schedule-package');
> await schedule.update(); // Grab the most recent schedule for the week
> assert(schedule.monday = {'A Period': { 'start': '8:25 AM', 'end': '9:45 AM'}})
> ```
> 
> Or whatever makes the most sense to you (just make sure that your documentation makes sense).

[Okay](https://www.npmjs.com/package/awesome-new-gunn-schedule-package)
