### ISSUE TITLE
Weird time render glitch

### ISSUE THREAD

**Issue by PooleHenry** [Orbiit/gunn-web-app#22]
![screenshot 2017-09-26 at 10 51 05 am](https://user-images.githubusercontent.com/29491154/30875755-6205aa40-a2a9-11e7-85d8-e1e12790652b.png)

Just says '_ left in flex'

**Comment by SheepTester** [comment]
Thanks for the screenshot! You're using the Materialize version that I decided to not use; I actually [remade the schedule thing](https://orbiit.github.io/gunn-web-app/schedule/apptest.html) and am working on [incorporating the pieces together](https://orbiit.github.io/gunn-web-app/appdesign.html) right now

However, the problem may also persist in the new schedule app, so I'll look into it

I should make a dialogue that tells people still on the Materialize version that a new version exists

Btw, if you're curious why I decided not to use the Materialize version:
- it was too big; it had to load jQuery, Materialize's CSS and JS, and many weights of the Roboto font
- the cache didn't work on my iPad so it's permanently broken :/
- it was not made in a way so that it could be easily put into an app
- remaking anything is a great opportunity to make something better anyways, since you can
  1. get feedback on your first version
  2. implement their ideas without turning your code into spagetti

  I plan to remake the entire app again (goal: follow my own design principles, keep ripple effect, add people's ideas), but that'll be in the very far future and I don't want to ruin it right now

I ended up stealing a lot of CSS from Materialize, which turned the CSS into spagetti. Next time I won't bother with the material guidelines anymore
