### ISSUE TITLE
Completely broken schedule?

### ISSUE THREAD

**Issue by CannotWin** [Orbiit/gunn-web-app#23]
I tried to access the app using https://orbiit.github.io/gunn-web-app/appdesign.html 
Screenshots show this.
![screenshot 2017-09-27 at 11 05 46 am](https://user-images.githubusercontent.com/32305919/30929624-d7f6c0d4-a373-11e7-99bc-154ffa2c5c3b.png)
Maybe I just don't have permissions or something...

-Aaryan Agrawal

**Comment by SheepTester** [comment]
oh! it could be adblock!

One of the URLs must include "ads" in it, maybe?

**Comment by SheepTester** [comment]
I see that it worked for you after a hard reload. I'll consider that as fixed. :)

(for anyone curious: the problem was that when I split the JavaScript into multiple files, some of the variables got misplaced and so there was an error "variable not defined" and things stopped working. This happened in `schedule.js`, which is why the schedule didn't appear)

**Comment by PooleHenry** [comment]
Lol
