### ISSUE TITLE
Swipe on mobile

### ISSUE THREAD

**Issue by Velosify** [Orbiit/gunn-web-app#26]
The separate [schedule](https://orbiit.github.io/gunn-web-app/schedule/) version can swipe between days on a touchscreen device
Perhaps this should be implemented to the UGWA?

_EDIT by Sean: fixing your markdown_

**Comment by SheepTester** [comment]
It doesn't follow material guidelines, but maybe I'll add it in UGWA 2

**Comment by SheepTester** [comment]
@Velosify how should I detect the difference between a scroll and a horizontal swipe?

Also, I think I might get rid of the sections and adopt a system similar to `/schedule`

**Comment by Velosify** [comment]
@SheepTester Google?
[stackoverflow?](https://stackoverflow.com/questions/2264072/detect-a-finger-swipe-through-javascript-on-the-iphone-and-android)
Problem with /schedule is that the animation to switch between days is slow on laptops/desktop

**Comment by SheepTester** [comment]
@Velosify The problem with detecting a swipe that way is that it makes normal scrolling slow and not as one would expect because the browser also has to run the JS to check if it would be blocked or not

[See this for a better worded version](https://developers.google.com/web/updates/2016/06/passive-event-listeners)

**Comment by SheepTester** [comment]
Also material design disrecommends this.
